#created on: Jan 29, 2012
package net.majakorpi.elasticity

import net.majakorpi.elasticity.model.Cluster
import net.majakorpi.elasticity.model.Metric
import net.majakorpi.elasticity.model.RuleOutput
import net.majakorpi.elasticity.model.ScalingAction
import net.majakorpi.elasticity.model.ScalingAction.ScalingType
import java.util.List

#declare any global variables here

rule "load-5 over 1"
  
    when
        $ruleOutput : RuleOutput()
        $clusters: List ()
        $cluster: Cluster() from $clusters
        $metric: Metric (name == "load_five", sum > 0.001) from $cluster.metrics
    then
        System.out.println("Fired!");
		$ruleOutput.add(new ScalingAction($cluster, ScalingType.MOAR, 1));
end
